name: Build VPN APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0 # Code ရာဇဝင်တစ်ခုလုံးကို ဆွဲယူရန်

      - name: Force Initialize Git Submodules
        run: |
          # Submodules တွေကို အတင်းအကျပ် အသစ်ပြန်ဆွဲယူခြင်း
          git submodule sync
          git submodule update --init --recursive --force

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 🌟 (၁) Debug အစား Release APK ကို ပြောင်း၍ Build လုပ်ခြင်း 🌟
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 🌟 (၂) GitHub Secrets ထဲမှ Keystore ဖြင့် App ကို Sign လုပ်ခြင်း 🌟
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ui/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # 🌟 (၃) Sign လုပ်ပြီးသား Official APK ကို Download ရယူနိုင်ရန် တင်ပေးခြင်း 🌟
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: MH-VPN-Signed-Release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 3
